In [31]:
import torch

In [32]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [33]:
t1.dtype

torch.float32

In [34]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [35]:
t3 = torch.tensor([[1.,2,3,4],
                   [5,6,7,8]])
t3

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [36]:
t4 = torch.tensor([[[1,2,3.,4],
                    [5,6,7,8]],
                   [[9,10,11,12],
                    [13,14,15,16]]])
t4

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]])

In [37]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [38]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [39]:
print(t3)
t3.shape

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


torch.Size([2, 4])

In [40]:
print(t4)
t4.shape

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]])


torch.Size([2, 2, 4])

In [41]:
t5 = torch.tensor([[1,2,3,4],
                  [2, 4],
                  [3, 2, 1]])
t5

ValueError: expected sequence of length 4 at dim 1 (got 2)

In [47]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [48]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [49]:
y.backward()
print('dy/dx = ', x.grad)
print('dy/dw = ', w.grad)
print('dy/db = ', b.grad)

dy/dx =  None
dy/dw =  tensor(3.)
dy/db =  tensor(1.)


In [50]:
t6 = torch.full((3,4), 45)
t6

tensor([[45, 45, 45, 45],
        [45, 45, 45, 45],
        [45, 45, 45, 45]])

In [51]:
t7 = torch.cat((t3, t6))
t7

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [45., 45., 45., 45.],
        [45., 45., 45., 45.],
        [45., 45., 45., 45.]])

In [52]:
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.8509,  0.8509,  0.8509,  0.8509],
        [ 0.8509,  0.8509,  0.8509,  0.8509],
        [ 0.8509,  0.8509,  0.8509,  0.8509]])

In [53]:
t9 = t8.reshape((5, 2, 2))
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568]],

        [[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.8509,  0.8509],
         [ 0.8509,  0.8509]],

        [[ 0.8509,  0.8509],
         [ 0.8509,  0.8509]],

        [[ 0.8509,  0.8509],
         [ 0.8509,  0.8509]]])

In [54]:
import numpy as np
x = np.array([[1,2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [55]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [43]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [45]:
z = y.numpy()
z, z.dtype

(array([[1., 2.],
        [3., 4.]]),
 dtype('float64'))